version: '3'
services:
  app:
    container_name: modern-portfolio
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3082:3000"
    volumes:
      - .:/app
    restart: always