name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: |
          cd /home/thomas-jan/Dev/Portfolio/modern-portfolio/
          git pull origin main
    
      - name: Docker
        run: |
          docker compose down
          docker compose up -d
         